---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: database
type: Opaque
data:
  mongodb-root-password: cGFzc3dvcmQxMjM=
  mongodb-password: cGFzc3dvcmQ=
  mongodb-replica-set-key: a2V5cmVwbGljYQ==
